import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import styles from "../styles/Home.module.css";

export default function Home({ contents }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>NEXT JS TEXT APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* 헤더 */}
      <Header />
      {/* 메뉴 */}
      <Nav />
      {/* 컨텐츠 */}
    </div>
  );
}

export async function getServerSideProps(context) {
  const menu = context.query.menu;

  const BASE_URL = "https://api.themoviedb.org";
  const API_KEY = "25695d3ad1911085af6aad954e05bc2f";

  const res = await fetch(
    `${BASE_URL}/3/discover/movie?api_key=${API_KEY}&language=kr&with_genres=${menu}`
  );
  const data = await res.json();

  console.log(data);
  return {
    props: {
      contents: data.results,
    },
  };
}
