import Head from "next/head";

export default function Home({ contents }) {
  return (
    <div>
      <Head>
        <title>S Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>메인페이지</h1>
    </div>
  );
}
